import { jsPDF } from 'jspdf'
import { fmtDate, fmtTime, fmtDuration, type Token, type Triage, type User, type Prescription } from './types'
import { bandLabel } from './tokens'

function header(doc: jsPDF, title: string) {
  doc.setFillColor(11, 100, 180)
  doc.rect(0, 0, 210, 26, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text('MediQ', 14, 12)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Rural public healthcare · Maharashtra', 14, 18.5)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 196, 16, { align: 'right' })
}

function footer(doc: jsPDF) {
  const y = 287
  doc.setFontSize(8)
  doc.setTextColor(120, 130, 145)
  doc.setFont('helvetica', 'normal')
  doc.text('Generated by MediQ · This is a computer-generated document and needs no signature.', 105, y, { align: 'center' })
}

function kv(doc: jsPDF, label: string, value: string, x: number, y: number): number {
  doc.setFontSize(9.5)
  doc.setTextColor(120, 130, 145)
  doc.setFont('helvetica', 'normal')
  doc.text(label, x, y)
  doc.setTextColor(15, 36, 64)
  doc.setFont('helvetica', 'bold')
  const lines = doc.splitTextToSize(value || '—', 170)
  doc.text(lines, x, y + 5)
  return y + 5 + lines.length * 5 + 3
}

export function downloadReceipt(
  token: Token & { id: string },
  triage: (Triage & { id: string }) | null,
  patient: User,
  doctor: User | null,
  prescription: (Prescription & { id: string }) | null,
) {
  const doc = new jsPDF()
  header(doc, 'e-Receipt')
  let y = 36
  doc.setFontSize(11)
  doc.setTextColor(15, 36, 64)
  doc.setFont('helvetica', 'bold')
  doc.text(`Token ${token.code}  ·  ${bandLabel(token.band)}`, 14, y)
  y += 4
  doc.setDrawColor(226, 234, 242)
  doc.line(14, y, 196, y)
  y += 8
  y = kv(doc, 'Date / time', `${fmtDate(token.createdAt)} · ${fmtTime(token.createdAt)} IST`, 14, y)
  y = kv(doc, 'Patient', `${patient.name}  ·  ABHA ${patient.abhaId || '—'}`, 14, y)
  y = kv(doc, 'Doctor', doctor ? `${doctor.name} (${doctor.specialization || ''})` : '—', 14, y)
  if (triage) y = kv(doc, 'Assessment', `Score ${triage.score}/100 · ${bandLabel(triage.band)}. ${triage.reasons.slice(0, 3).join(' ')}`, 14, y)
  if (token.notes) y = kv(doc, 'Visit summary', token.notes, 14, y)
  if (token.callDurationSec) y = kv(doc, 'Consultation duration', fmtDuration(token.callDurationSec), 14, y)
  if (prescription && prescription.items.length > 0) {
    y = kv(doc, 'Medicines', prescription.items.map(m => `${m.name} — ${m.dosage}, ${m.frequency}, ${m.durationDays} days`).join('\n'), 14, y)
  }
  footer(doc)
  doc.save(`MediQ-receipt-${token.code}.pdf`)
}

export function downloadPrescription(
  rx: Prescription & { id: string },
  patient: User,
  doctor: User,
) {
  const doc = new jsPDF()
  header(doc, 'e-Prescription')
  let y = 36
  doc.setFontSize(11)
  doc.setTextColor(15, 36, 64)
  doc.setFont('helvetica', 'bold')
  doc.text(`Rx · Token ${rx.tokenId ? '' : ''}${fmtDate(rx.createdAt)}`, 14, y)
  y += 4
  doc.setDrawColor(226, 234, 242)
  doc.line(14, y, 196, y)
  y += 8
  y = kv(doc, 'Doctor', `${doctor.name} · ${doctor.qualifications || ''}\n${doctor.specialization || ''} · ${doctor.clinic || ''}`, 14, y)
  y = kv(doc, 'Patient', `${patient.name} · Age ${patient.age ?? '—'} · ABHA ${patient.abhaId || '—'}`, 14, y)
  doc.setFontSize(9.5)
  doc.setTextColor(120, 130, 145)
  doc.setFont('helvetica', 'normal')
  doc.text('Medicines', 14, y)
  y += 6
  doc.setTextColor(15, 36, 64)
  rx.items.forEach((m, i) => {
    doc.setFont('helvetica', 'bold')
    doc.text(`${i + 1}. ${m.name}`, 14, y)
    doc.setFont('helvetica', 'normal')
    const detail = `${m.dosage} · ${m.frequency} · ${m.durationDays} days`
    doc.text(detail, 14, y + 5)
    y += 12
  })
  if (rx.advice) y = kv(doc, 'Advice', rx.advice, 14, y)
  footer(doc)
  doc.save(`MediQ-prescription-${rx.id.slice(-6)}.pdf`)
}
